# =============================================================================
# DevPulse — developer commands.
# Run `make help` to see what's available.
# =============================================================================

# Use bash, fail fast.
SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c
.DEFAULT_GOAL := help

# Allow override: e.g. `make logs SERVICE=postgres`
SERVICE ?=
COMPOSE := docker compose

# ----- Help ------------------------------------------------------------------
.PHONY: help
help: ## Show this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n\nTargets:\n"} \
		/^[a-zA-Z0-9_.-]+:.*?##/ { printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2 }' $(MAKEFILE_LIST)

# ----- Lifecycle -------------------------------------------------------------
.PHONY: up down restart logs ps build rebuild
up: ## Start the full stack in the background.
	$(COMPOSE) up -d --build
	@echo
	@echo "API:      http://localhost:8000"
	@echo "Docs:     http://localhost:8000/docs"
	@echo "Healthz:  http://localhost:8000/healthz"

down: ## Stop and remove containers (keeps volumes).
	$(COMPOSE) down

nuke: ## Stop containers AND wipe volumes (deletes Postgres data).
	$(COMPOSE) down -v

restart: ## Restart all services (or SERVICE=name for one).
	$(COMPOSE) restart $(SERVICE)

logs: ## Tail logs (use SERVICE=api to follow one service).
	$(COMPOSE) logs -f --tail=200 $(SERVICE)

ps: ## Show running services.
	$(COMPOSE) ps

build: ## Build images without starting.
	$(COMPOSE) build

rebuild: ## Force a clean rebuild of all images.
	$(COMPOSE) build --no-cache

# ----- Backend dev (inside the api container) -------------------------------
.PHONY: shell psql redis-cli
shell: ## Open a shell inside the api container.
	$(COMPOSE) exec api bash

psql: ## Open a psql prompt against the local DB.
	$(COMPOSE) exec postgres psql -U $${POSTGRES_USER:-devpulse} -d $${POSTGRES_DB:-devpulse}

redis-cli: ## Open redis-cli against the local Redis.
	$(COMPOSE) exec redis redis-cli

# ----- Quality gates ---------------------------------------------------------
.PHONY: lint format typecheck test test-cov check
lint: ## Run ruff lint.
	$(COMPOSE) run --rm --no-deps api ruff check .

format: ## Run ruff format (writes changes).
	$(COMPOSE) run --rm --no-deps api ruff format .

typecheck: ## Run mypy strict.
	$(COMPOSE) run --rm --no-deps api mypy app

test: ## Run pytest.
	$(COMPOSE) run --rm api pytest

test-cov: ## Run pytest with coverage.
	$(COMPOSE) run --rm api pytest --cov=app --cov-report=term-missing

check: lint typecheck test ## Run everything CI would run.

# ----- Migrations (wired up in step 6 of Phase 1) ----------------------------
.PHONY: migrate migration revision
migrate: ## Apply migrations.
	$(COMPOSE) exec api alembic upgrade head

revision: ## Create a new autogenerated migration. Use MSG="add foo".
	$(COMPOSE) exec api alembic revision --autogenerate -m "$(MSG)"
