"""SQLAlchemy declarative base + reusable mixins.

The `Base` class here is what every ORM model inherits from. Two things make
this file slightly more than a one-liner:

1. A *naming convention* on MetaData. Without one, Postgres auto-generates
   index and constraint names like `ix_5e1f48d3`, which makes Alembic
   migrations non-deterministic. With a convention, Alembic produces
   stable, human-readable names that survive being re-run on a fresh DB.

2. A `TimestampMixin` that gives every model `created_at` and `updated_at`
   columns set by Postgres itself (not by Python). Audit fields are
   table-stakes in production schemas.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# ----------------------------------------------------------------------------
# Naming convention. SQLAlchemy uses these tokens to build constraint names:
#   %(table_name)s, %(column_0_name)s, %(constraint_name)s, %(referred_table_name)s
# Prefixes: ix_ (index), uq_ (unique), ck_ (check), fk_ (foreign key), pk_ (primary key)
# This convention is the de-facto standard in the SQLAlchemy community.
# ----------------------------------------------------------------------------
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    """Single declarative base for every model in the app.

    Every `models.py` in `app/modules/<domain>/` imports this `Base`.
    Alembic's `target_metadata = Base.metadata` then sees every registered
    table when generating autogenerated migrations.
    """

    metadata = metadata


class TimestampMixin:
    """Adds created_at / updated_at to a model.

    `server_default=func.now()` makes Postgres set the value — not Python.
    This is important because clock drift between app servers is a real
    thing, and the database is the source of truth.

    `onupdate=func.now()` updates the column on every UPDATE. Note: this
    fires on the SQLAlchemy side; for ORM-bypassing bulk updates the DB
    trigger is more bulletproof, but for our use-case ORM-level is enough.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
