"""Custom SQLAlchemy column types.

Empty for now. Reserved for project-specific column types as they emerge.

Earlier this file held a `Citext` (Postgres case-insensitive text) wrapper,
but autogenerated Alembic migrations don't render TypeDecorators cleanly,
which forced hand-edits on every revision. We dropped that and now
normalize emails / slugs in the service layer instead. The `citext`
extension remains enabled in `postgres/init.sql` for potential future use.
"""
